name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        check-latest: true

    - name: Run go mod tidy
      run: cd app && go mod tidy
      
    - name: Read version
      id: version
      run: echo "VERSION=$(cat .version)" >> $GITHUB_OUTPUT
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      if: github.event_name != 'pull_request'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/corespark-io/recaptcha-server:${{ steps.version.outputs.VERSION }} .
        docker tag ghcr.io/corespark-io/recaptcha-server:${{ steps.version.outputs.VERSION }} ghcr.io/corespark-io/recaptcha-server:latest

    - name: Push Docker image
      if: github.event_name != 'pull_request'
      run: |
        docker push ghcr.io/corespark-io/recaptcha-server:${{ steps.version.outputs.VERSION }}
        docker push ghcr.io/corespark-io/recaptcha-server:latest